import '#app/globals.css';
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { LinguiClientProvider } from '#app/_components/lingui-client-provider.tsx';
import { TooltipProvider } from '#app/_components/tooltip.tsx';
import { cn } from '#app/_libs/cn.ts';
import { inter } from '#app/_libs/fonts.ts';
import linguiConfig from '#app/_libs/locales/lingui.config.ts';
import { withLingui } from '#app/_libs/locales/withLingui.tsx';
import { getI18nMessage } from '#app/_queries/i18n.ts';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default withLingui(async function RootLayout({
    children,
    params: { lang },
}) {
    return (
        <html
            lang={lang}
            className={cn(
                'antialiased [font-synthesis-weight:none]',
                inter.variable,
            )}
        >
            <body>
                <LinguiClientProvider
                    initialLocale={lang}
                    initialMessages={await getI18nMessage(lang)}
                >
                    <SessionProvider>
                        <TooltipProvider>{children}</TooltipProvider>
                    </SessionProvider>
                </LinguiClientProvider>
            </body>
        </html>
    );
});

export async function generateStaticParams() {
    return linguiConfig.locales.map((lang) => ({ lang }));
}
