import type mongoose from "mongoose";

export const MongooseSchemaOptions: mongoose.SchemaOptions = {
    strictQuery: true,
    overwriteModels: true,
    strict: process.env.NODE_ENV === "development" ? "throw" : true,
    autoCreate: process.env.NODE_ENV === "development",
    bufferCommands: process.env.NODE_ENV === "development",
    autoIndex: process.env.NODE_ENV === "development",
    // @ts-expect-error
    transactionAsyncLocalStorage: true,
};

/**
 * We create a separate options since mongoose {@link mongoose.set} doesn't allow to set _id to false
 */
export const TypegooseSchemaOptions: mongoose.SchemaOptions = {
    ...MongooseSchemaOptions,
    // NOTE (xuwam - 15/10/2024): Don't add _id: we'll generate the id manually instead. This is to avoid the
    // _id being generated by mongoose which is an ObjectId
    _id: false,
};
