import { modelOptions, setGlobalOptions } from '@typegoose/typegoose';
import { deleteModel } from 'mongoose';
import { typeid } from 'typeid-js';

setGlobalOptions({
    schemaOptions: {
        // NOTE (xuwam - 15/10/2024): Don't add _id: we'll generate the id manually instead. This is to avoid the
        // _id being generated by mongoose which is an ObjectId
        _id: false,
    },
    globalOptions: {
        disableGlobalCaching: process.env.NODE_ENV === 'development',
    },
});

if (process.env.NODE_ENV === 'development') {
    deleteModel(/.+/);
}

export function generateIdWithPrefix(prefix: string) {
    return () => typeid(prefix).toString();
}

@modelOptions({
    schemaOptions: {
        timestamps: {
            createdAt: 'created_at',
            updatedAt: 'updated_at',
        },
    },
})
class Base {
    created_at!: Date;
    updated_at!: Date;
}

export { Base };
