name: check
run-name: Run continuous integration code
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - stage
      - main

env:
  FAKER_SEED: ${{ github.run_number }}

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - run: corepack enable

      - uses: actions/setup-node@v4.0.2
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - name: Cache turbo build setup
        id: cache-turbo-restore
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Reset changed package.json due to install
        run: git checkout -- package.json apps/**/package.json packages/**/package.json configs/**/package.json

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - run: npx turbo test test:storybook format-and-lint check-types check-circular

      - name: Always turbo cache
        if: always() && steps.cache-turbo-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          path: .turbo

      - uses: actions/upload-artifact@v4
        if: '!cancelled() && failure()'
        with:
          name: test-results
          path: apps/portal/storybook-static/
          retention-days: 2
